package com.superman.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class ClAddressBook implements Serializable {
    /**
     * 
     * @mbggenerated
     */
    private String bookId;

    /**
     * 
     * @mbggenerated
     */
    private String ownerId;

    /**
     * 
     * @mbggenerated
     */
    private String friendId;

    /**
     * 
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @mbggenerated
     */
    public String getBookId() {
        return bookId;
    }

    /**
     * 
     * @param bookId 
     * @mbggenerated
     */
    public void setBookId(String bookId) {
        this.bookId = bookId == null ? null : bookId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * 
     * @param ownerId 
     * @mbggenerated
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * 
     * @param friendId 
     * @mbggenerated
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId == null ? null : friendId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * 
     * @param rowAddTime 
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bookId=").append(bookId);
        sb.append(", ownerId=").append(ownerId);
        sb.append(", friendId=").append(friendId);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}