package com.superman.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class ClAlbumInfo implements Serializable {
    /**
     * 相册ID
     * @mbggenerated
     */
    private String albumId;

    /**
     * 
     * @mbggenerated
     */
    private String ownerId;

    /**
     * 相册图片存储路径
     * @mbggenerated
     */
    private String picPath;

    /**
     * 
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_album_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 相册ID
     * @mbggenerated
     */
    public String getAlbumId() {
        return albumId;
    }

    /**
     * 相册ID
     * @param albumId 相册ID
     * @mbggenerated
     */
    public void setAlbumId(String albumId) {
        this.albumId = albumId == null ? null : albumId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * 
     * @param ownerId 
     * @mbggenerated
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * 相册图片存储路径
     * @mbggenerated
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * 相册图片存储路径
     * @param picPath 相册图片存储路径
     * @mbggenerated
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * 
     * @param rowAddTime 
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_album_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", albumId=").append(albumId);
        sb.append(", ownerId=").append(ownerId);
        sb.append(", picPath=").append(picPath);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}