package com.superman.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class ClGuideInfo implements Serializable {
    /**
     * 
     * @mbggenerated
     */
    private String guideId;

    /**
     * 关联用户ID
     * @mbggenerated
     */
    private String userId;

    /**
     * 昵称
     * @mbggenerated
     */
    private String nickName;

    /**
     * 头像路径
     * @mbggenerated
     */
    private String headPicPath;

    /**
     * 性别
     * @mbggenerated
     */
    private String sex;

    /**
     * 职业
     * @mbggenerated
     */
    private String profession;

    /**
     * 个性签名
     * @mbggenerated
     */
    private String signature;

    /**
     * 导游类型(0业务导游、1职业导游、2游戏陪玩、3同城服务）
     * @mbggenerated
     */
    private Integer type;

    /**
     * 通讯录密码
     * @mbggenerated
     */
    private String bookPasswd;

    /**
     * 0-每次访问均不需要密码，1-第一次访问需要密码，2-每次访问均需要密码
     * @mbggenerated
     */
    private Integer bookPassType;

    /**
     * 
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_guide_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @mbggenerated
     */
    public String getGuideId() {
        return guideId;
    }

    /**
     * 
     * @param guideId 
     * @mbggenerated
     */
    public void setGuideId(String guideId) {
        this.guideId = guideId == null ? null : guideId.trim();
    }

    /**
     * 关联用户ID
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * 关联用户ID
     * @param userId 关联用户ID
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * 昵称
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * 昵称
     * @param nickName 昵称
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * 头像路径
     * @mbggenerated
     */
    public String getHeadPicPath() {
        return headPicPath;
    }

    /**
     * 头像路径
     * @param headPicPath 头像路径
     * @mbggenerated
     */
    public void setHeadPicPath(String headPicPath) {
        this.headPicPath = headPicPath == null ? null : headPicPath.trim();
    }

    /**
     * 性别
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * 性别
     * @param sex 性别
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * 职业
     * @mbggenerated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * 职业
     * @param profession 职业
     * @mbggenerated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * 个性签名
     * @mbggenerated
     */
    public String getSignature() {
        return signature;
    }

    /**
     * 个性签名
     * @param signature 个性签名
     * @mbggenerated
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * 导游类型(0业务导游、1职业导游、2游戏陪玩、3同城服务）
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * 导游类型(0业务导游、1职业导游、2游戏陪玩、3同城服务）
     * @param type 导游类型(0业务导游、1职业导游、2游戏陪玩、3同城服务）
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 通讯录密码
     * @mbggenerated
     */
    public String getBookPasswd() {
        return bookPasswd;
    }

    /**
     * 通讯录密码
     * @param bookPasswd 通讯录密码
     * @mbggenerated
     */
    public void setBookPasswd(String bookPasswd) {
        this.bookPasswd = bookPasswd == null ? null : bookPasswd.trim();
    }

    /**
     * 0-每次访问均不需要密码，1-第一次访问需要密码，2-每次访问均需要密码
     * @mbggenerated
     */
    public Integer getBookPassType() {
        return bookPassType;
    }

    /**
     * 0-每次访问均不需要密码，1-第一次访问需要密码，2-每次访问均需要密码
     * @param bookPassType 0-每次访问均不需要密码，1-第一次访问需要密码，2-每次访问均需要密码
     * @mbggenerated
     */
    public void setBookPassType(Integer bookPassType) {
        this.bookPassType = bookPassType;
    }

    /**
     * 
     * @mbggenerated
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * 
     * @param rowAddTime 
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_guide_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", guideId=").append(guideId);
        sb.append(", userId=").append(userId);
        sb.append(", nickName=").append(nickName);
        sb.append(", headPicPath=").append(headPicPath);
        sb.append(", sex=").append(sex);
        sb.append(", profession=").append(profession);
        sb.append(", signature=").append(signature);
        sb.append(", type=").append(type);
        sb.append(", bookPasswd=").append(bookPasswd);
        sb.append(", bookPassType=").append(bookPassType);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}