package com.superman.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class ClMessageInfo implements Serializable {
    /**
     * 
     * @mbggenerated
     */
    private String messageId;

    /**
     * 
     * @mbggenerated
     */
    private String title;

    /**
     * 
     * @mbggenerated
     */
    private String body;

    /**
     * 
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @mbggenerated
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * 
     * @param messageId 
     * @mbggenerated
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * 
     * @param title 
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getBody() {
        return body;
    }

    /**
     * 
     * @param body 
     * @mbggenerated
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * 
     * @param rowAddTime 
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", messageId=").append(messageId);
        sb.append(", title=").append(title);
        sb.append(", body=").append(body);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}