package com.superman.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class ClOrderInfo implements Serializable {
    /**
     * 
     * @mbggenerated
     */
    private String orderId;

    /**
     * 
     * @mbggenerated
     */
    private String orderNo;

    /**
     * 
     * @mbggenerated
     */
    private Long amount;

    /**
     * 
     * @mbggenerated
     */
    private String status;

    /**
     * 
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_order_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * 
     * @param orderId 
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * 
     * @param orderNo 
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * 
     * @param amount 
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * 
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * 
     * @param status 
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * 
     * @param rowAddTime 
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_order_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", amount=").append(amount);
        sb.append(", status=").append(status);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}