package com.superman.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class ClSetting implements Serializable {
    /**
     * 
     * @mbggenerated
     */
    private String settingId;

    /**
     * 
     * @mbggenerated
     */
    private String key;

    /**
     * 
     * @mbggenerated
     */
    private String value;

    /**
     * 
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_setting
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @mbggenerated
     */
    public String getSettingId() {
        return settingId;
    }

    /**
     * 
     * @param settingId 
     * @mbggenerated
     */
    public void setSettingId(String settingId) {
        this.settingId = settingId == null ? null : settingId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getKey() {
        return key;
    }

    /**
     * 
     * @param key 
     * @mbggenerated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * 
     * @param value 
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * 
     * @param rowAddTime 
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_setting
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", settingId=").append(settingId);
        sb.append(", key=").append(key);
        sb.append(", value=").append(value);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}