package com.superman.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class MenuInfo implements Serializable {
    /**
     * 
     * @mbggenerated
     */
    private String menuId;

    /**
     * 
     * @mbggenerated
     */
    private String text;

    /**
     * 
     * @mbggenerated
     */
    private String parentId;

    /**
     * 
     * @mbggenerated
     */
    private String expanded;

    /**
     * 
     * @mbggenerated
     */
    private String code;

    /**
     * 
     * @mbggenerated
     */
    private String url;

    /**
     * 
     * @mbggenerated
     */
    private String leaf;

    /**
     * 
     * @mbggenerated
     */
    private String system;

    /**
     * 
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * 
     * @param menuId 
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getText() {
        return text;
    }

    /**
     * 
     * @param text 
     * @mbggenerated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * 
     * @param parentId 
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getExpanded() {
        return expanded;
    }

    /**
     * 
     * @param expanded 
     * @mbggenerated
     */
    public void setExpanded(String expanded) {
        this.expanded = expanded == null ? null : expanded.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * 
     * @param code 
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * 
     * @param url 
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getLeaf() {
        return leaf;
    }

    /**
     * 
     * @param leaf 
     * @mbggenerated
     */
    public void setLeaf(String leaf) {
        this.leaf = leaf == null ? null : leaf.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public String getSystem() {
        return system;
    }

    /**
     * 
     * @param system 
     * @mbggenerated
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * 
     * @param rowAddTime 
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", text=").append(text);
        sb.append(", parentId=").append(parentId);
        sb.append(", expanded=").append(expanded);
        sb.append(", code=").append(code);
        sb.append(", url=").append(url);
        sb.append(", leaf=").append(leaf);
        sb.append(", system=").append(system);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}