package com.superman.dal.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {
    /**
     * 
     * @mbggenerated
     */
    private String userId;

    /**
     * 用户名
     * @mbggenerated
     */
    private String userName;

    /**
     * 用户昵称
     * @mbggenerated
     */
    private String nickName;

    /**
     * 登录密码
     * @mbggenerated
     */
    private String passwd;

    /**
     * 
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * 
     * @param userId 
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * 用户名
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 用户名
     * @param userName 用户名
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 用户昵称
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * 用户昵称
     * @param nickName 用户昵称
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * 登录密码
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * 登录密码
     * @param passwd 登录密码
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * 
     * @mbggenerated
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * 
     * @param rowAddTime 
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", nickName=").append(nickName);
        sb.append(", passwd=").append(passwd);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}