package com.superman.dal.mybatis.maps;

import com.superman.dal.mybatis.model.ClAddressBook;
import com.superman.dal.mybatis.model.ClAddressBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ClAddressBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int countByExample(ClAddressBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int deleteByExample(ClAddressBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int deleteByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int insert(ClAddressBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int insertSelective(ClAddressBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    List<ClAddressBook> selectByExampleWithRowbounds(ClAddressBookExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    List<ClAddressBook> selectByExample(ClAddressBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    ClAddressBook selectByPrimaryKey(String bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") ClAddressBook record, @Param("example") ClAddressBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int updateByExample(@Param("record") ClAddressBook record, @Param("example") ClAddressBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int updateByPrimaryKeySelective(ClAddressBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_address_book
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int updateByPrimaryKey(ClAddressBook record);
}