package com.superman.dal.mybatis.maps;

import com.superman.dal.mybatis.model.ClMessageInfo;
import com.superman.dal.mybatis.model.ClMessageInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ClMessageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int countByExample(ClMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int deleteByExample(ClMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int deleteByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int insert(ClMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int insertSelective(ClMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    List<ClMessageInfo> selectByExampleWithRowbounds(ClMessageInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    List<ClMessageInfo> selectByExample(ClMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    ClMessageInfo selectByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") ClMessageInfo record, @Param("example") ClMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int updateByExample(@Param("record") ClMessageInfo record, @Param("example") ClMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int updateByPrimaryKeySelective(ClMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_message_info
     *
     * @mbggenerated Fri Dec 02 11:13:40 CST 2016
     */
    int updateByPrimaryKey(ClMessageInfo record);
}